name: Angular Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Clone devextreme-angular repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme-angular ./devextreme-angular-repo

    - name: Clone devextreme-angular repo
      run: |
        BASE_BRANCH=$(node -p -e "require('./package.json').version.slice(0, 4).replace('.', '_')")
        test -d ./devextreme-angular-repo || git clone -b $BASE_BRANCH https://github.com/devexpress/devextreme-angular ./devextreme-angular-repo

    - name: Install packages in devextreme repo
      run: npm install --no-audit --no-fund

    - name: Build devextreme repo
      run: npm run build-dist

    - name: Install devextreme package
      run: |
        cd ./devextreme-angular-repo/packages/devextreme-angular
        npm install --save-dev ../../../artifacts/npm/devextreme

    - name: Run npm install for devextreme-angular repo
      run: |
        cd ./devextreme-angular-repo
        npm install --no-audit --no-fund

    - name: Build with Angular 7
      run: |
        cd ./devextreme-angular-repo
        npm run build

    - name: Run tests with Angular 7
      run: |
        cd ./devextreme-angular-repo
        npx lerna run --scope devextreme-angular gulp -- run.tests